-- GENERATED by Programs/tools/generate_hornet_catalog.py - do not edit.
-- Template: Programs/tools/templates/HornetLinkNative.lua.in
--[[
  HornetLinkNative.lua - Hornet Link native F/A-18C exporter
  ============================================================
  Talks to hornet-link.exe directly. DCS-BIOS is NOT required; if it is
  installed this script chains its hooks and both keep working.

  INSTALL (pick one)
  ------------------------------------------------------------
  a) Copy this file to  Saved Games\DCS\Scripts\HornetLinkNative.lua
     and add these lines at the END of Saved Games\DCS\Scripts\Export.lua:

        local hlnOk, hlnErr = pcall(dofile, lfs.writedir() .. "Scripts/HornetLinkNative.lua")
        if not hlnOk then log.write("HornetLinkNative", log.ERROR, tostring(hlnErr)) end

  b) Or paste this whole file at the end of Export.lua.

  WHAT IT DOES
  ------------------------------------------------------------
  - Runs only in the aircraft named below. In any other aircraft it stays
    quiet and tells the bridge "active 0" once per second.
  - Reads the cockpit (argument values and display text) for catalogue
    controls only, and sends values that changed, keyed by catalogue id.
    Every second it sends everything again (full refresh).
  - Receives typed input events from the bridge and applies them with
    DCS's own performClickableAction.

  WIRE FORMAT (UDP, plain text so you can read it in a packet capture)
  ------------------------------------------------------------
  exporter -> bridge, 127.0.0.1:HLN_BRIDGE_PORT, one or more datagrams per tick:
      HLN 2 <catalog hash> <aircraft> <active 0|1> <full 0|1>
      <id>=<value>          e.g.  0101=1      (position, lamp, analog 0-65535)
      <id>=T:<text>         e.g.  0240=T:  1234   (% escapes %, =, control bytes)
  bridge -> exporter, this script listens on 127.0.0.1:HLN_LISTEN_PORT:
      <id> SET <n>  |  <id> STEP <+/-n>  |  <id> PRESS  |  <id> RELEASE  |  <id> ANALOG <0-65535>
      e.g. "0101 SET 1" puts the Master Arm switch to ARM.

  DCS DATA
  ------------------------------------------------------------
  Rows marked "DCS data: dcsbios (TEMPORARY)" use device/command/argument
  numbers taken from DCS-BIOS until native data is extracted. See
  docs/DCS_DATA_PROVENANCE.md.
]]

-- -- Settings you may change ------------------------------------------------
local HLN_HOST          = "127.0.0.1"
local HLN_BRIDGE_PORT   = 42003   -- hornet-link.exe listens here
local HLN_LISTEN_PORT   = 42004   -- this script listens here for inputs
local HLN_SAMPLE_HZ     = 30      -- cockpit reads per second
local HLN_FULL_REFRESH  = 1.0     -- seconds between full refreshes
local HLN_MAX_DATAGRAM  = 1200    -- bytes
local HLN_RELEASE_TICKS = 3       -- frames before a magnetic switch press is released

-- -- Generated catalogue ------------------------------------------------------
local HLN_AIRCRAFT      = "FA-18C_hornet"
local HLN_CATALOG_HASH  = "0x737DD343"
local HLN_CATALOG_VER   = "0.1.0"

local HLN_CONTROLS = {
    { id = 0x0101, name = "MASTER_ARM.MASTER_ARM", type = "switch", count = 2, style = "tumb", device = 23, command = 3003, arg = 49, values = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0102, name = "MASTER_ARM.MODE_AA", type = "button", count = 2, style = "button", device = 23, command = 3001, arg = 458 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0103, name = "MASTER_ARM.MODE_AG", type = "button", count = 2, style = "button", device = 23, command = 3002, arg = 459 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0104, name = "MASTER_ARM.AA_LT", type = "lamp", style = "lamp", arg = 47, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0105, name = "MASTER_ARM.AG_LT", type = "lamp", style = "lamp", arg = 48, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0106, name = "MASTER_ARM.READY_LT", type = "lamp", style = "lamp", arg = 44, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0107, name = "MASTER_ARM.DISCH_LT", type = "lamp", style = "lamp", arg = 45, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0108, name = "MASTER_ARM.FIRE_EXT", type = "button", count = 2, style = "button", device = 12, command = 3008, arg = 46 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0109, name = "MASTER_ARM.EMER_JETT", type = "button", count = 2, style = "button", device = 23, command = 3004, arg = 50 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0201, name = "UFC.KEY_0", type = "button", count = 2, style = "button", device = 25, command = 3018, arg = 120 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0202, name = "UFC.KEY_1", type = "button", count = 2, style = "button", device = 25, command = 3019, arg = 111 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0203, name = "UFC.KEY_2", type = "button", count = 2, style = "button", device = 25, command = 3020, arg = 112 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0204, name = "UFC.KEY_3", type = "button", count = 2, style = "button", device = 25, command = 3021, arg = 113 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0205, name = "UFC.KEY_4", type = "button", count = 2, style = "button", device = 25, command = 3022, arg = 114 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0206, name = "UFC.KEY_5", type = "button", count = 2, style = "button", device = 25, command = 3023, arg = 115 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0207, name = "UFC.KEY_6", type = "button", count = 2, style = "button", device = 25, command = 3024, arg = 116 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0208, name = "UFC.KEY_7", type = "button", count = 2, style = "button", device = 25, command = 3025, arg = 117 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0209, name = "UFC.KEY_8", type = "button", count = 2, style = "button", device = 25, command = 3026, arg = 118 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x020A, name = "UFC.KEY_9", type = "button", count = 2, style = "button", device = 25, command = 3027, arg = 119 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x020B, name = "UFC.KEY_CLR", type = "button", count = 2, style = "button", device = 25, command = 3028, arg = 121 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x020C, name = "UFC.KEY_ENT", type = "button", count = 2, style = "button", device = 25, command = 3029, arg = 122 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x020D, name = "UFC.OS1", type = "button", count = 2, style = "button", device = 25, command = 3010, arg = 100 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x020E, name = "UFC.OS2", type = "button", count = 2, style = "button", device = 25, command = 3011, arg = 101 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x020F, name = "UFC.OS3", type = "button", count = 2, style = "button", device = 25, command = 3012, arg = 102 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0210, name = "UFC.OS4", type = "button", count = 2, style = "button", device = 25, command = 3013, arg = 103 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0211, name = "UFC.OS5", type = "button", count = 2, style = "button", device = 25, command = 3014, arg = 106 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0212, name = "UFC.IP", type = "button", count = 2, style = "button", device = 25, command = 3015, arg = 99 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0213, name = "UFC.AP", type = "button", count = 2, style = "button", device = 25, command = 3001, arg = 128 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0214, name = "UFC.IFF", type = "button", count = 2, style = "button", device = 25, command = 3002, arg = 129 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0215, name = "UFC.TCN", type = "button", count = 2, style = "button", device = 25, command = 3003, arg = 130 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0216, name = "UFC.ILS", type = "button", count = 2, style = "button", device = 25, command = 3004, arg = 131 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0217, name = "UFC.DL", type = "button", count = 2, style = "button", device = 25, command = 3005, arg = 132 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0218, name = "UFC.BCN", type = "button", count = 2, style = "button", device = 25, command = 3006, arg = 133 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0219, name = "UFC.ONOFF", type = "button", count = 2, style = "button", device = 25, command = 3007, arg = 134 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x021A, name = "UFC.EMCON", type = "button", count = 2, style = "button", device = 25, command = 3017, arg = 110 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x021B, name = "UFC.COMM1_PULL", type = "button", count = 2, style = "button", device = 25, command = 3008, arg = 125 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x021C, name = "UFC.COMM2_PULL", type = "button", count = 2, style = "button", device = 25, command = 3009, arg = 127 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x021D, name = "UFC.ADF", type = "switch", count = 3, style = "tumb", device = 25, command = 3016, arg = 107, values = { -1, 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x021E, name = "UFC.COMM1_VOL", type = "axis", style = "axis", device = 25, command = 3030, arg = 108, range = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x021F, name = "UFC.COMM2_VOL", type = "axis", style = "axis", device = 25, command = 3031, arg = 123, range = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0220, name = "UFC.BRT", type = "axis", style = "axis", device = 25, command = 3032, arg = 109, range = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0221, name = "UFC.COMM1_CHANNEL", type = "rotary", style = "step", device = 25, command = 3033, values = { -0.03, 0.03 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0222, name = "UFC.COMM2_CHANNEL", type = "rotary", style = "step", device = 25, command = 3034, values = { -0.03, 0.03 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0240, name = "UFC.SCRATCHPAD_NUMBER", type = "text", length = 8, style = "indication", display = 6, field = "UFC_ScratchPadNumberDisplay" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0241, name = "UFC.SCRATCHPAD_STRING_1", type = "text", length = 2, style = "indication", display = 6, field = "UFC_ScratchPadString1Display" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0242, name = "UFC.SCRATCHPAD_STRING_2", type = "text", length = 2, style = "indication", display = 6, field = "UFC_ScratchPadString2Display" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0243, name = "UFC.COMM1_DISPLAY", type = "text", length = 2, style = "indication", display = 6, field = "UFC_Comm1Display" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0244, name = "UFC.COMM2_DISPLAY", type = "text", length = 2, style = "indication", display = 6, field = "UFC_Comm2Display" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0245, name = "UFC.OPTION_DISPLAY_1", type = "text", length = 4, style = "indication", display = 6, field = "UFC_OptionDisplay1" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0246, name = "UFC.OPTION_DISPLAY_2", type = "text", length = 4, style = "indication", display = 6, field = "UFC_OptionDisplay2" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0247, name = "UFC.OPTION_DISPLAY_3", type = "text", length = 4, style = "indication", display = 6, field = "UFC_OptionDisplay3" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0248, name = "UFC.OPTION_DISPLAY_4", type = "text", length = 4, style = "indication", display = 6, field = "UFC_OptionDisplay4" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0249, name = "UFC.OPTION_DISPLAY_5", type = "text", length = 4, style = "indication", display = 6, field = "UFC_OptionDisplay5" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x024A, name = "UFC.OPTION_CUEING_1", type = "text", length = 1, style = "indication", display = 6, field = "UFC_OptionCueing1" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x024B, name = "UFC.OPTION_CUEING_2", type = "text", length = 1, style = "indication", display = 6, field = "UFC_OptionCueing2" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x024C, name = "UFC.OPTION_CUEING_3", type = "text", length = 1, style = "indication", display = 6, field = "UFC_OptionCueing3" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x024D, name = "UFC.OPTION_CUEING_4", type = "text", length = 1, style = "indication", display = 6, field = "UFC_OptionCueing4" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x024E, name = "UFC.OPTION_CUEING_5", type = "text", length = 1, style = "indication", display = 6, field = "UFC_OptionCueing5" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0301, name = "APU.APU_CONTROL", type = "switch", count = 2, style = "magnetic", device = 12, command = 3001, arg = 375 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0302, name = "APU.ENGINE_CRANK", type = "switch", count = 3, style = "magnetic3", device = 12, neg_command = 3002, pos_command = 3003, arg = 377, values = { -1, 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0303, name = "APU.APU_READY_LT", type = "lamp", style = "lamp", arg = 376, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0401, name = "FIRE_CAUTION.MASTER_CAUTION_LT", type = "lamp", style = "lamp", arg = 13, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0402, name = "FIRE_CAUTION.MASTER_CAUTION_RESET", type = "button", count = 2, style = "button", device = 9, command = 3008, arg = 14 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0403, name = "FIRE_CAUTION.FIRE_LEFT_LT", type = "lamp", style = "lamp", arg = 10, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0404, name = "FIRE_CAUTION.LEFT_FIRE_BTN", type = "button", count = 2, style = "button", device = 12, command = 3010, arg = 11 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0405, name = "FIRE_CAUTION.LEFT_FIRE_COVER", type = "switch", count = 2, style = "tumb", device = 12, command = 3012, arg = 12, values = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0406, name = "FIRE_CAUTION.FIRE_RIGHT_LT", type = "lamp", style = "lamp", arg = 26, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0407, name = "FIRE_CAUTION.RIGHT_FIRE_BTN", type = "button", count = 2, style = "button", device = 12, command = 3011, arg = 27 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0408, name = "FIRE_CAUTION.RIGHT_FIRE_COVER", type = "switch", count = 2, style = "tumb", device = 12, command = 3013, arg = 28, values = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0409, name = "FIRE_CAUTION.FIRE_APU_LT", type = "lamp", style = "lamp", arg = 29, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x040A, name = "FIRE_CAUTION.APU_FIRE_BTN", type = "button", count = 2, style = "button", device = 12, command = 3009, arg = 30 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0501, name = "LH_ADVISORY.L_BLEED", type = "lamp", style = "lamp", arg = 17, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0502, name = "LH_ADVISORY.R_BLEED", type = "lamp", style = "lamp", arg = 18, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0503, name = "LH_ADVISORY.SPD_BRK", type = "lamp", style = "lamp", arg = 19, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0504, name = "LH_ADVISORY.STBY", type = "lamp", style = "lamp", arg = 20, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0505, name = "LH_ADVISORY.L_BAR_RED", type = "lamp", style = "lamp", arg = 21, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0506, name = "LH_ADVISORY.REC", type = "lamp", style = "lamp", arg = 22, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0507, name = "LH_ADVISORY.L_BAR_GREEN", type = "lamp", style = "lamp", arg = 23, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0508, name = "LH_ADVISORY.XMIT", type = "lamp", style = "lamp", arg = 24, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0509, name = "LH_ADVISORY.ASPJ_OH", type = "lamp", style = "lamp", arg = 25, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x050A, name = "LH_ADVISORY.GO", type = "lamp", style = "lamp", arg = 15, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x050B, name = "LH_ADVISORY.NO_GO", type = "lamp", style = "lamp", arg = 16, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0601, name = "HUD_CONTROL.SYM_REJ", type = "selector", count = 3, style = "tumb", device = 34, command = 3001, arg = 140, values = { 0, 0.1, 0.2 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0602, name = "HUD_CONTROL.SYM_BRT", type = "axis", style = "axis", device = 34, command = 3002, arg = 141, range = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0603, name = "HUD_CONTROL.SYM_BRT_SELECT", type = "switch", count = 2, style = "tumb", device = 34, command = 3003, arg = 142, values = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0604, name = "HUD_CONTROL.BLACK_LVL", type = "axis", style = "axis", device = 34, command = 3004, arg = 143, range = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0605, name = "HUD_CONTROL.VIDEO_CONTROL", type = "selector", count = 3, style = "tumb", device = 34, command = 3005, arg = 144, values = { 0, 0.1, 0.2 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0606, name = "HUD_CONTROL.BALANCE", type = "axis", style = "axis", device = 34, command = 3006, arg = 145, range = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0607, name = "HUD_CONTROL.AOA_INDEXER_BRT", type = "axis", style = "axis", device = 34, command = 3007, arg = 146, range = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0608, name = "HUD_CONTROL.ALT", type = "switch", count = 2, style = "tumb", device = 34, command = 3008, arg = 147, values = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0609, name = "HUD_CONTROL.ATT", type = "switch", count = 3, style = "tumb", device = 34, command = 3009, arg = 148, values = { -1, 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0701, name = "SPIN_RECOVERY.SPIN_LT", type = "lamp", style = "lamp", arg = 137, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0702, name = "SPIN_RECOVERY.SPIN_RECOVERY_COVER", type = "switch", count = 2, style = "tumb", device = 2, command = 3008, arg = 139, values = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0703, name = "SPIN_RECOVERY.SPIN_RECOVERY", type = "switch", count = 2, style = "tumb", device = 2, command = 3009, arg = 138, values = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0704, name = "SPIN_RECOVERY.IR_COOL", type = "switch", count = 3, style = "tumb", device = 23, command = 3013, arg = 135, values = { 0, 0.1, 0.2 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0705, name = "SPIN_RECOVERY.HMD_BRT", type = "axis", style = "axis", device = 58, command = 3001, arg = 136, range = { 0, 0.75 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0801, name = "AOA_INDEXER.HIGH", type = "lamp", style = "lamp", arg = 4, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0802, name = "AOA_INDEXER.NORMAL", type = "lamp", style = "lamp", arg = 5, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0803, name = "AOA_INDEXER.LOW", type = "lamp", style = "lamp", arg = 6, threshold = 0.3 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0901, name = "IFEI.MODE", type = "button", count = 2, style = "button", device = 33, command = 3001, arg = 168 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0902, name = "IFEI.QTY", type = "button", count = 2, style = "button", device = 33, command = 3002, arg = 169 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0903, name = "IFEI.UP", type = "button", count = 2, style = "button", device = 33, command = 3003, arg = 170 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0904, name = "IFEI.DOWN", type = "button", count = 2, style = "button", device = 33, command = 3004, arg = 171 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0905, name = "IFEI.ZONE", type = "button", count = 2, style = "button", device = 33, command = 3005, arg = 172 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0906, name = "IFEI.ET", type = "button", count = 2, style = "button", device = 33, command = 3006, arg = 173 },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0907, name = "IFEI.BRT", type = "axis", style = "axis", device = 33, command = 3007, arg = 174, range = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0940, name = "IFEI.BINGO", type = "text", length = 5, style = "indication", display = 5, field = "txt_BINGO" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0941, name = "IFEI.FUEL_UP", type = "text", length = 6, style = "indication", display = 5, field = "txt_FUEL_UP" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0942, name = "IFEI.FUEL_DOWN", type = "text", length = 6, style = "indication", display = 5, field = "txt_FUEL_DOWN" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0943, name = "IFEI.RPM_L", type = "text", length = 3, style = "indication", display = 5, field = "txt_RPM_L" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0944, name = "IFEI.RPM_R", type = "text", length = 3, style = "indication", display = 5, field = "txt_RPM_R" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0945, name = "IFEI.TEMP_L", type = "text", length = 3, style = "indication", display = 5, field = "txt_TEMP_L" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0946, name = "IFEI.TEMP_R", type = "text", length = 3, style = "indication", display = 5, field = "txt_TEMP_R" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0947, name = "IFEI.FF_L", type = "text", length = 3, style = "indication", display = 5, field = "txt_FF_L" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0948, name = "IFEI.FF_R", type = "text", length = 3, style = "indication", display = 5, field = "txt_FF_R" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0949, name = "IFEI.CLOCK_H", type = "text", length = 2, style = "indication", display = 5, field = "txt_CLOCK_H" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x094A, name = "IFEI.CLOCK_M", type = "text", length = 2, style = "indication", display = 5, field = "txt_CLOCK_M" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x094B, name = "IFEI.CLOCK_S", type = "text", length = 2, style = "indication", display = 5, field = "txt_CLOCK_S" },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0A01, name = "ANTENNA_SELECT.COMM1_ANT", type = "switch", count = 3, style = "tumb", device = 50, command = 3001, arg = 373, values = { -1, 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0A02, name = "ANTENNA_SELECT.IFF_ANT", type = "switch", count = 3, style = "tumb", device = 50, command = 3002, arg = 374, values = { -1, 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0B01, name = "STBY_COMPASS.HEADING", type = "gauge", style = "gauge", arg = 149, range = { 0, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0B02, name = "STBY_COMPASS.PITCH", type = "gauge", style = "gauge", arg = 150, range = { -1, 1 } },  -- DCS data: dcsbios (TEMPORARY)
    { id = 0x0B03, name = "STBY_COMPASS.BANK", type = "gauge", style = "gauge", arg = 151, range = { -1, 1 } },  -- DCS data: dcsbios (TEMPORARY)
}

-- -- State --------------------------------------------------------------------
local hln_tx, hln_rx = nil, nil
local hln_byId = {}
for _, c in ipairs(HLN_CONTROLS) do hln_byId[c.id] = c end
local hln_last = {}            -- id -> last value string sent
local hln_nextSample = 0
local hln_nextFull = 0
local hln_active = false
local hln_releases = {}        -- { device, command, ticks }

-- -- Helpers ------------------------------------------------------------------
local function hln_clamp(v, lo, hi)
    if v < lo then return lo elseif v > hi then return hi end
    return v
end

local function hln_nearest(values, v)
    local best, bestDist = 0, math.huge
    for i, x in ipairs(values) do
        local d = math.abs(x - v)
        if d < bestDist then best, bestDist = i - 1, d end
    end
    return best
end

local function hln_escape(s)
    return (s:gsub("[%%=%c\128-\255]", function(ch) return string.format("%%%02X", ch:byte()) end))
end

local function hln_padLeft(s, n)
    s = s or ""
    if #s > n then return s:sub(1, n) end
    return string.rep(" ", n - #s) .. s
end

-- list_indication() returns blocks separated by dashed lines:
--   -----------------------------------------
--   <field name>
--   <value line(s)>
--   }
local function hln_parseIndication(id)
    local out = {}
    local ok, raw = pcall(list_indication, id)
    if not ok or type(raw) ~= "string" then return out end
    local key, lines = nil, {}
    local function flush()
        if key then out[key] = table.concat(lines, "\n") end
        key, lines = nil, {}
    end
    for line in (raw .. "\n"):gmatch("([^\n]*)\n") do
        if line:match("^%-%-%-%-%-%-") then
            flush()
            key = false            -- next line is the field name
        elseif key == false then
            key = line
        elseif key and line ~= "}" and line ~= "{" and line ~= "children are {" then
            lines[#lines + 1] = line
        end
    end
    flush()
    return out
end

-- -- Reading the cockpit ------------------------------------------------------
local function hln_read(c, dev0, displays)
    if c.style == "indication" then
        local fields = displays[c.display]
        if not fields then
            fields = hln_parseIndication(c.display)
            displays[c.display] = fields
        end
        return "T:" .. hln_escape(hln_padLeft(fields[c.field], c.length))
    end
    if not c.arg or c.style == "step" then return nil end
    local v = dev0:get_argument_value(c.arg)
    if c.style == "tumb" or c.style == "magnetic3" then
        return tostring(hln_nearest(c.values, v))
    elseif c.style == "button" or c.style == "magnetic" then
        return (v > 0.5) and "1" or "0"
    elseif c.style == "lamp" then
        return (v >= (c.threshold or 0.3)) and "1" or "0"
    elseif c.style == "axis" or c.style == "gauge" then
        local lo, hi = c.range[1], c.range[2]
        return tostring(math.floor(hln_clamp((v - lo) / (hi - lo), 0, 1) * 65535 + 0.5))
    end
    return nil
end

local function hln_send(lines, full)
    if not hln_tx then return end
    local header = string.format("HLN 2 %s %s %d %d\n", HLN_CATALOG_HASH, HLN_AIRCRAFT,
                                 hln_active and 1 or 0, full and 1 or 0)
    local buf = header
    for _, l in ipairs(lines) do
        if #buf + #l + 1 > HLN_MAX_DATAGRAM then
            hln_tx:sendto(buf, HLN_HOST, HLN_BRIDGE_PORT)
            buf = header
        end
        buf = buf .. l .. "\n"
    end
    hln_tx:sendto(buf, HLN_HOST, HLN_BRIDGE_PORT)
end

local function hln_sample(now)
    local full = now >= hln_nextFull
    if full then hln_nextFull = now + HLN_FULL_REFRESH end
    if not hln_active then
        if full then hln_send({}, true) end
        return
    end
    local dev0 = GetDevice(0)
    if not dev0 then return end
    local displays, lines = {}, {}
    for _, c in ipairs(HLN_CONTROLS) do
        local ok, value = pcall(hln_read, c, dev0, displays)
        if ok and value and (full or hln_last[c.id] ~= value) then
            hln_last[c.id] = value
            lines[#lines + 1] = string.format("%04X=%s", c.id, value)
        end
    end
    if full or #lines > 0 then hln_send(lines, full) end
end

-- -- Applying inputs ----------------------------------------------------------
local function hln_click(device, command, value)
    local dev = GetDevice(device)
    if dev then dev:performClickableAction(command, value) end
end

local function hln_releaseLater(device, command)
    hln_releases[#hln_releases + 1] = { device = device, command = command, ticks = HLN_RELEASE_TICKS }
end

local function hln_currentPosition(c)
    local dev0 = GetDevice(0)
    if not dev0 or not c.arg then return 0 end
    local v = dev0:get_argument_value(c.arg)
    if c.values then return hln_nearest(c.values, v) end
    return (v > 0.5) and 1 or 0
end

local function hln_apply(c, action, n)
    local s = c.style
    if s == "button" then
        if action == "PRESS" or (action == "SET" and n == 1) then hln_click(c.device, c.command, 1)
        elseif action == "RELEASE" or (action == "SET" and n == 0) then hln_click(c.device, c.command, 0) end
    elseif s == "tumb" then
        local pos = n
        if action == "STEP" then pos = hln_currentPosition(c) + n end
        if action == "SET" or action == "STEP" then
            pos = hln_clamp(pos, 0, #c.values - 1)
            hln_click(c.device, c.command, c.values[pos + 1])
        end
    elseif s == "magnetic" then
        if action == "SET" and hln_currentPosition(c) ~= n then
            hln_click(c.device, c.command, 1)
            hln_releaseLater(c.device, c.command)
        end
    elseif s == "magnetic3" then
        if action ~= "SET" then return end
        local cur = hln_currentPosition(c)
        if n == 2 and cur ~= 2 then
            hln_click(c.device, c.pos_command, 1); hln_releaseLater(c.device, c.pos_command)
        elseif n == 0 and cur ~= 0 then
            hln_click(c.device, c.neg_command, -1); hln_releaseLater(c.device, c.neg_command)
        elseif n == 1 then
            if cur == 2 then hln_click(c.device, c.pos_command, 0)
            elseif cur == 0 then hln_click(c.device, c.neg_command, 0) end
        end
    elseif s == "axis" then
        local lo, hi = c.range[1], c.range[2]
        local v = n
        if action == "STEP" then
            local dev0 = GetDevice(0)
            local raw = dev0 and dev0:get_argument_value(c.arg) or lo
            v = (raw - lo) / (hi - lo) * 65535 + n
        end
        if action == "ANALOG" or action == "STEP" or action == "SET" then
            hln_click(c.device, c.command, lo + hln_clamp(v, 0, 65535) / 65535 * (hi - lo))
        end
    elseif s == "step" and action == "STEP" then
        local value = (n > 0) and c.values[2] or c.values[1]
        for _ = 1, math.min(math.abs(n), 32) do hln_click(c.device, c.command, value) end
    end
end

local function hln_receive()
    if not hln_rx then return end
    for _ = 1, 64 do
        local data = hln_rx:receive()
        if not data then return end
        for line in data:gmatch("[^\n]+") do
            local idHex, action, arg = line:match("^(%x%x%x%x) (%u+) ?([%+%-]?%d*)$")
            local c = idHex and hln_byId[tonumber(idHex, 16)]
            if c and hln_active then
                pcall(hln_apply, c, action, tonumber(arg) or 0)
            end
        end
    end
end

local function hln_tickReleases()
    for i = #hln_releases, 1, -1 do
        local r = hln_releases[i]
        r.ticks = r.ticks - 1
        if r.ticks <= 0 then
            hln_click(r.device, r.command, 0)
            table.remove(hln_releases, i)
        end
    end
end

-- -- DCS export hooks (chained, so DCS-BIOS and others keep working) ------------
local hln_prevStart = LuaExportStart
function LuaExportStart()
    if hln_prevStart then hln_prevStart() end
    package.path = package.path .. ";.\\LuaSocket\\?.lua"
    package.cpath = package.cpath .. ";.\\LuaSocket\\?.dll"
    local okSocket, sock = pcall(require, "socket")
    if not okSocket then
        log.write("HornetLinkNative", log.ERROR, "LuaSocket not available")
        return
    end
    hln_tx = sock.udp()
    hln_tx:settimeout(0)
    hln_rx = sock.udp()
    hln_rx:setsockname(HLN_HOST, HLN_LISTEN_PORT)
    hln_rx:settimeout(0)
    hln_nextSample, hln_nextFull, hln_last = 0, 0, {}
    log.write("HornetLinkNative", log.INFO, "catalogue " .. HLN_CATALOG_VER .. " hash " .. HLN_CATALOG_HASH)
end

local hln_prevStop = LuaExportStop
function LuaExportStop()
    if hln_prevStop then hln_prevStop() end
    if hln_tx then hln_tx:close(); hln_tx = nil end
    if hln_rx then hln_rx:close(); hln_rx = nil end
end

local hln_prevBefore = LuaExportBeforeNextFrame
function LuaExportBeforeNextFrame()
    if hln_prevBefore then hln_prevBefore() end
    local okRx, errRx = pcall(hln_receive)
    if not okRx then log.write("HornetLinkNative", log.ERROR, tostring(errRx)) end
end

local hln_prevAfter = LuaExportAfterNextFrame
function LuaExportAfterNextFrame()
    if hln_prevAfter then hln_prevAfter() end
    pcall(hln_tickReleases)
    local now = LoGetModelTime() or 0
    if now + 5 < hln_nextSample then hln_nextSample, hln_nextFull = 0, 0 end -- mission restarted
    if now < hln_nextSample then return end
    hln_nextSample = now + 1 / HLN_SAMPLE_HZ
    local selfData = LoGetSelfData()
    local wasActive = hln_active
    hln_active = (selfData ~= nil and selfData.Name == HLN_AIRCRAFT)
    if hln_active and not wasActive then
        hln_last = {}
        hln_nextFull = 0
    end
    local okTx, errTx = pcall(hln_sample, now)
    if not okTx then log.write("HornetLinkNative", log.ERROR, tostring(errTx)) end
end
