#pragma once
// GENERATED by Programs/tools/generate_hornet_catalog.py - do not edit.
// Source: catalog/protocol_v2.json. See docs/PROTOCOL_V2.md.

#include <stdint.h>

namespace hn {

constexpr uint8_t kProtocolVersion = 2;
constexpr uint16_t kHeaderBytes = 6;
constexpr uint16_t kCrcBytes = 2;
constexpr uint16_t kMaxPayload = 120;
constexpr uint16_t kMaxName = 16;
constexpr uint32_t kTimingBaud = 250000UL;
constexpr uint32_t kTimingByteTimeUs = 40UL;
constexpr uint32_t kTimingTurnaroundUs = 100UL;
constexpr uint32_t kTimingReplyTimeoutMs = 8UL;
constexpr uint32_t kTimingMissedPollsBeforeDrop = 5UL;
constexpr uint32_t kTimingDiscoverIntervalMs = 1000UL;
constexpr uint32_t kTimingDiscoverSlots = 8UL;
constexpr uint32_t kTimingDiscoverSlotMs = 2UL;

/// Bus / link addresses.
enum Address : uint8_t {
    ADDR_BROADCAST = 0, ///< Every node processes the frame. Never used as a source.
    ADDR_FIRST_SLAVE = 1, ///< Lowest RS-485 slave address.
    ADDR_LAST_SLAVE = 239, ///< Highest RS-485 slave address.
    ADDR_BRIDGE = 253, ///< The PC bridge (hornet-link.exe).
    ADDR_LINK_NODE = 254, ///< The board attached to the PC over USB: a bus master or a standalone panel.
    ADDR_UNASSIGNED = 255, ///< A slave that has no bus address yet. Only used as a source in HELLO during discovery.
};

/// Message types (first header byte after version/dst/src).
enum MsgType : uint8_t {
    MSG_HELLO_REQUEST = 0x01, ///< Ask a node to identify itself. The node answers with HELLO.
    MSG_HELLO = 0x02, ///< Identity and capabilities. role is a bit set of ROLE_*.
    MSG_DESCRIBE_REQUEST = 0x03, ///< Ask for one page of the node's control list.
    MSG_DESCRIBE = 0x04, ///< Controls the node owns. role 0 = input (node -> sim), 1 = output (sim -> node).
    MSG_SUBSCRIBE = 0x05, ///< Replace the node's output subscription. scope is one of SUBSCRIBE_*.
    MSG_STATE = 0x10, ///< Sim state keyed by catalogue id. kind is one of VALUE_*: BOOL/POSITION value is u8, ANALOG is u16, TEXT is [len:u8][bytes].
    MSG_INPUT = 0x11, ///< Cockpit input events. action is one of ACTION_*. The frame sequence number is used for duplicate detection and ACK.
    MSG_SYNC_REQUEST = 0x12, ///< Ask the node to report the physical position of every input it owns.
    MSG_SYNC_REPORT = 0x13, ///< Physical positions (position index, or 0-65535 for axes). flags bit 0 = last page of the report.
    MSG_MODE = 0x20, ///< Change operating mode. mode is one of MODE_*.
    MSG_MODE_ACK = 0x21, ///< The mode the node applied.
    MSG_ACK = 0x30, ///< The frame with sequence acked_seq was accepted.
    MSG_NACK = 0x31, ///< The frame was rejected. reason is one of NACK_*.
    MSG_DIAG_REQUEST = 0x40, ///< Ask for diagnostic counters.
    MSG_DIAG = 0x41, ///< Counters since boot plus an optional short text message.
    MSG_CONFIG = 0x50, ///< Change a setting. key is one of CFG_*. The node answers ACK or NACK.
    MSG_HEARTBEAT = 0x60, ///< Keeps an idle USB link alive.
    MSG_POLL = 0x70, ///< The addressed slave may transmit exactly one frame now.
    MSG_POLL_EMPTY = 0x71, ///< Reply to POLL when the slave has nothing to send.
    MSG_DISCOVER = 0x72, ///< Slaves that have not been polled recently answer HELLO in one random slot.
    MSG_BUS_EVENT = 0x73, ///< A slave joined, dropped off or has an address conflict. event is one of BUS_*.
};

enum RoleCode : uint8_t {
    ROLE_PANEL = 1, ///< Owns inputs and/or outputs.
    ROLE_BUS_MASTER = 2, ///< Relays an RS-485 bus.
    ROLE_BUS_SLAVE = 4, ///< Sits on an RS-485 bus.
};

enum ValueCode : uint8_t {
    VALUE_BOOL = 0, ///< u8, 0 or 1 (lamps).
    VALUE_POSITION = 1, ///< u8 position index (switches, selectors, buttons).
    VALUE_ANALOG = 2, ///< u16, 0-65535 (axes, gauges).
    VALUE_TEXT = 3, ///< [len:u8][bytes], fixed catalogue length.
};

enum NackCode : uint8_t {
    NACK_UNKNOWN_CONTROL = 1, ///< The control id is not in the catalogue.
    NACK_BAD_VALUE = 2, ///< The value or action does not fit the control type.
    NACK_WRONG_MODE = 3, ///< Inputs are ignored in the current mode.
    NACK_BAD_FRAME = 4, ///< The payload is malformed.
    NACK_CATALOG_MISMATCH = 5, ///< The node was built against a different catalogue hash.
    NACK_UNSUPPORTED = 6, ///< The message or config key is not supported.
};

enum ModeCode : uint8_t {
    MODE_SIM = 0, ///< Live DCS data; inputs forwarded to DCS.
    MODE_LAMP_TEST = 1, ///< All outputs on; inputs not forwarded.
    MODE_MAINTENANCE = 2, ///< Panel self-check; DCS not required.
    MODE_WIRING_TEST = 3, ///< Each input reports its name when actuated; inputs not forwarded.
};

enum SubscribeCode : uint8_t {
    SUBSCRIBE_CLEAR = 0, ///< No outputs.
    SUBSCRIBE_CONTROLS = 1, ///< The listed control ids.
    SUBSCRIBE_PANELS = 2, ///< Every output in the listed panel ids (high byte of a control id).
    SUBSCRIBE_ALL = 3, ///< Every output.
};

enum BusCode : uint8_t {
    BUS_JOIN = 1, ///< The slave answered for the first time, or again after being dropped. The bridge should resend full state.
    BUS_DROP = 2, ///< The slave missed too many polls and is now polled slowly.
    BUS_CONFLICT = 3, ///< Two boards answered with the same bus address.
};

enum DescribeRoleCode : uint8_t {
    DESCRIBE_ROLE_INPUT = 0, ///< Cockpit to sim.
    DESCRIBE_ROLE_OUTPUT = 1, ///< Sim to cockpit.
};

enum ActionCode : uint8_t {
    ACTION_SET_POSITION = 0, ///< Move to position index arg.
    ACTION_STEP = 1, ///< Relative step; arg is a signed 16-bit count.
    ACTION_PRESS = 2, ///< Momentary press.
    ACTION_RELEASE = 3, ///< Momentary release.
    ACTION_ANALOG = 4, ///< Absolute analog value 0-65535.
};

enum CfgCode : uint8_t {
    CFG_BUS_ADDRESS = 1, ///< [address:u8] Change the slave bus address (RAM only until SAVE).
    CFG_CALIBRATION = 2, ///< [control_id:u16][min:u16][max:u16] Axis calibration.
    CFG_SAVE = 3, ///< Persist settings through the sketch's save hook.
};

/// Readable name of a message type (for logs and the ASCII debug mode).
inline const char* msgTypeName(uint8_t t) {
    switch (t) {
    case MSG_HELLO_REQUEST: return "HELLO_REQUEST";
    case MSG_HELLO: return "HELLO";
    case MSG_DESCRIBE_REQUEST: return "DESCRIBE_REQUEST";
    case MSG_DESCRIBE: return "DESCRIBE";
    case MSG_SUBSCRIBE: return "SUBSCRIBE";
    case MSG_STATE: return "STATE";
    case MSG_INPUT: return "INPUT";
    case MSG_SYNC_REQUEST: return "SYNC_REQUEST";
    case MSG_SYNC_REPORT: return "SYNC_REPORT";
    case MSG_MODE: return "MODE";
    case MSG_MODE_ACK: return "MODE_ACK";
    case MSG_ACK: return "ACK";
    case MSG_NACK: return "NACK";
    case MSG_DIAG_REQUEST: return "DIAG_REQUEST";
    case MSG_DIAG: return "DIAG";
    case MSG_CONFIG: return "CONFIG";
    case MSG_HEARTBEAT: return "HEARTBEAT";
    case MSG_POLL: return "POLL";
    case MSG_POLL_EMPTY: return "POLL_EMPTY";
    case MSG_DISCOVER: return "DISCOVER";
    case MSG_BUS_EVENT: return "BUS_EVENT";
    default: return "UNKNOWN";
    }
}

/// Readable name of a NACK reason.
inline const char* nackName(uint8_t r) {
    switch (r) {
    case NACK_UNKNOWN_CONTROL: return "UNKNOWN_CONTROL";
    case NACK_BAD_VALUE: return "BAD_VALUE";
    case NACK_WRONG_MODE: return "WRONG_MODE";
    case NACK_BAD_FRAME: return "BAD_FRAME";
    case NACK_CATALOG_MISMATCH: return "CATALOG_MISMATCH";
    case NACK_UNSUPPORTED: return "UNSUPPORTED";
    default: return "UNKNOWN";
    }
}

} // namespace hn
