#!/usr/bin/env python3
"""Generate every Hornet Link v2 artefact from the two source files.

Sources (edit these):
  catalog/fa18c.json        F/A-18C control catalogue
  catalog/protocol_v2.json  Protocol v2 message/enum specification

Outputs (never edit by hand):
  libraries/HornetLink/src/generated/HornetF18C.h     typed controls + flash tables
  libraries/HornetLink/src/protocol/HnSpec.h           protocol constants
  Programs/dcsbios-serial-bridge/lua/HornetLinkNative.lua  DCS exporter
  docs/F18C_CONTROL_REFERENCE.md                        per-panel reference
  docs/PROTOCOL_V2_MESSAGES.md                          message tables
  docs/DCS_DATA_PROVENANCE.md                           temporary-data register

Usage:
  python3 Programs/tools/generate_hornet_catalog.py          # write outputs
  python3 Programs/tools/generate_hornet_catalog.py --check  # fail if stale
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "catalog" / "fa18c.json"
PROTOCOL = ROOT / "catalog" / "protocol_v2.json"
LUA_TEMPLATE = ROOT / "Programs" / "tools" / "templates" / "HornetLinkNative.lua.in"

OUT_CPP = ROOT / "libraries" / "HornetLink" / "src" / "generated" / "HornetF18C.h"
OUT_SPEC = ROOT / "libraries" / "HornetLink" / "src" / "protocol" / "HnSpec.h"
OUT_LUA = ROOT / "Programs" / "dcsbios-serial-bridge" / "lua" / "HornetLinkNative.lua"
OUT_REF = ROOT / "docs" / "F18C_CONTROL_REFERENCE.md"
OUT_MSG = ROOT / "docs" / "PROTOCOL_V2_MESSAGES.md"
OUT_PROV = ROOT / "docs" / "DCS_DATA_PROVENANCE.md"

HEADER_NOTE = "GENERATED by Programs/tools/generate_hornet_catalog.py - do not edit."

KINDS = {  # catalogue type -> C++ Kind enumerator
    "switch": "Switch", "selector": "Selector", "button": "Button", "axis": "Axis",
    "rotary": "Rotary", "lamp": "Lamp", "gauge": "Gauge", "text": "Text",
}
INPUT_TYPES = {"switch", "selector", "button", "axis", "rotary"}
STYLES = {
    "switch": {"tumb", "magnetic", "magnetic3"},
    "selector": {"tumb"},
    "button": {"button"},
    "axis": {"axis"},
    "rotary": {"step"},
    "lamp": {"lamp"},
    "gauge": {"gauge"},
    "text": {"indication"},
}
FLAGS = {"guard", "magnetic"}
IDENT = re.compile(r"^[A-Z][A-Z0-9_]*$")
CODE = re.compile(r"^[A-Za-z][A-Za-z0-9]*$")
# Macros defined by one or more Arduino cores; these would break generated enums.
ARDUINO_MACROS = {
    "HIGH", "LOW", "INPUT", "OUTPUT", "INPUT_PULLUP", "DEFAULT", "EXTERNAL", "INTERNAL",
    "CHANGE", "RISING", "FALLING", "LSBFIRST", "MSBFIRST", "PI", "HALF_PI", "TWO_PI",
    "DEG_TO_RAD", "RAD_TO_DEG", "SERIAL", "DISPLAY", "BIN", "HEX", "OCT", "DEC",
}


class CatalogError(Exception):
    pass


def camel(key):
    return "".join(part[:1].upper() + part[1:].lower() for part in key.split("_"))


def fnv1a32(data):
    h = 0x811C9DC5
    for b in data:
        h ^= b
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h


def load_catalog(path=CATALOG):
    cat = json.loads(path.read_text(encoding="utf-8"))
    validate(cat)
    return cat


def validate(cat):
    if cat.get("schema") != 1:
        raise CatalogError("unsupported catalogue schema")
    sources = cat.get("dcs_data_sources", {})
    seen_panels, seen_panel_keys, seen_codes = set(), set(), set()
    for p in cat["panels"]:
        where = f"panel {p.get('key')}"
        if not isinstance(p.get("id"), int) or not 1 <= p["id"] <= 255:
            raise CatalogError(f"{where}: id must be 1..255")
        if p["id"] in seen_panels:
            raise CatalogError(f"{where}: duplicate panel id {p['id']}")
        if not IDENT.match(p["key"]) or p["key"] in seen_panel_keys:
            raise CatalogError(f"{where}: key must be unique UPPER_SNAKE_CASE")
        if not CODE.match(p["code"]) or p["code"] in seen_codes:
            raise CatalogError(f"{where}: code must be a unique C++ identifier")
        seen_panels.add(p["id"])
        seen_panel_keys.add(p["key"])
        seen_codes.add(p["code"])
        ids, keys, cpp_names = set(), set(), set()
        for c in p["controls"]:
            cw = f"{p['key']}.{c.get('key')}"
            if not isinstance(c.get("id"), int) or not 1 <= c["id"] <= 255:
                raise CatalogError(f"{cw}: id must be 1..255")
            if c["id"] in ids:
                raise CatalogError(f"{cw}: duplicate control id {c['id']}")
            if not IDENT.match(c["key"]) or c["key"] in keys:
                raise CatalogError(f"{cw}: key must be unique UPPER_SNAKE_CASE")
            cpp = camel(c["key"])
            if cpp in cpp_names or cpp == p["code"] + "Panel":
                raise CatalogError(f"{cw}: C++ name {cpp} collides")
            ids.add(c["id"])
            keys.add(c["key"])
            cpp_names.add(cpp)
            t = c.get("type")
            if t not in KINDS:
                raise CatalogError(f"{cw}: unknown type {t}")
            pos = c.get("positions")
            if t in ("switch", "selector", "button"):
                if not isinstance(pos, list):
                    raise CatalogError(f"{cw}: {t} needs positions")
                if t == "switch" and len(pos) not in (2, 3):
                    raise CatalogError(f"{cw}: a switch has 2 or 3 positions")
                if t == "selector" and not 2 <= len(pos) <= 32:
                    raise CatalogError(f"{cw}: a selector has 2..32 positions")
                if t == "button" and pos != ["RELEASED", "PRESSED"]:
                    raise CatalogError(f"{cw}: button positions are RELEASED, PRESSED")
                if len(set(pos)) != len(pos):
                    raise CatalogError(f"{cw}: duplicate position names")
                for name in pos:
                    if not IDENT.match(name) or name in ARDUINO_MACROS:
                        raise CatalogError(f"{cw}: bad position name {name}")
            elif pos is not None:
                raise CatalogError(f"{cw}: {t} must not list positions")
            if t == "text":
                if not isinstance(c.get("length"), int) or not 1 <= c["length"] <= 32:
                    raise CatalogError(f"{cw}: text length must be 1..32")
            elif "length" in c:
                raise CatalogError(f"{cw}: only text controls have a length")
            for f in c.get("flags", []):
                if f not in FLAGS:
                    raise CatalogError(f"{cw}: unknown flag {f}")
            dcs = c.get("dcs")
            if dcs is not None:
                if dcs.get("source") not in sources:
                    raise CatalogError(f"{cw}: dcs.source must name a dcs_data_sources entry")
                if dcs.get("style") not in STYLES[t]:
                    raise CatalogError(f"{cw}: dcs.style {dcs.get('style')} does not fit {t}")
                vals = dcs.get("values")
                if dcs["style"] in ("tumb", "magnetic3") and (not vals or len(vals) != len(pos)):
                    raise CatalogError(f"{cw}: dcs.values needs one value per position")
            if not isinstance(c.get("verified"), bool):
                raise CatalogError(f"{cw}: verified must be true or false")


def all_controls(cat):
    out = []
    for p in cat["panels"]:
        for c in p["controls"]:
            out.append((p, c, (p["id"] << 8) | c["id"]))
    out.sort(key=lambda t: t[2])
    return out


def canonical(cat):
    """Protocol-relevant content only: ids, names, types, positions, lengths."""
    lines = [f"schema={cat['schema']};aircraft={cat['aircraft']}"]
    for p, c, cid in all_controls(cat):
        pos = "|".join(c.get("positions", []))
        lines.append(f"{cid:04X};{p['key']}.{c['key']};{c['type']};{pos};{c.get('length', 0)}")
    return "\n".join(lines) + "\n"


def catalog_hash(cat):
    return fnv1a32(canonical(cat).encode("utf-8"))


def count_of(c):
    if c["type"] == "text":
        return c["length"]
    return len(c.get("positions", []))


def c_string(s):
    return json.dumps(s)  # JSON escaping is valid C for printable ASCII


# ── C++ / Arduino header ───────────────────────────────────────────────────

def render_cpp(cat):
    h = catalog_hash(cat)
    controls = all_controls(cat)
    o = []
    o.append("#pragma once")
    o.append(f"// {HEADER_NOTE}")
    o.append(f"// Source: catalog/fa18c.json (catalogue {cat['catalog_version']}).")
    o.append("//")
    o.append("// Typed F/A-18C controls for sketches and the bridge. Use the names, never")
    o.append("// the numbers: e.g. Hornet::MasterArm::MasterArm, Hornet::MasterArm::MasterArm.ARM.")
    o.append("")
    o.append('#include "../HornetTypes.h"')
    o.append("")
    o.append("namespace Hornet {")
    o.append("")
    o.append("/// FNV-1a hash of the protocol-relevant catalogue content (ids, names, types,")
    o.append("/// positions, text lengths). Sent in HELLO; the bridge warns on mismatch.")
    o.append(f"constexpr uint32_t kCatalogHash = 0x{h:08X}UL;")
    o.append(f"constexpr uint16_t kCatalogControlCount = {len(controls)};")
    o.append(f"#define HORNET_CATALOG_VERSION {c_string(cat['catalog_version'])}")
    o.append("")
    for p in cat["panels"]:
        o.append(f"/// {p['name']}")
        o.append(f"namespace {p['code']} {{")
        o.append(f"constexpr uint8_t kPanelId = {p['id']};")
        for c in p["controls"]:
            cid = (p["id"] << 8) | c["id"]
            kind = KINDS[c["type"]]
            n = count_of(c)
            name = camel(c["key"])
            base = f"Control<Kind::{kind}, {n}>"
            desc = c["name"]
            if c.get("positions"):
                desc += " - " + " / ".join(c["positions"])
            if c["type"] == "text":
                desc += f" - {c['length']} characters"
            o.append(f"/// {desc}")
            body = f"constexpr {name}_t() : {base}(0x{cid:04X}) {{}}"
            if c.get("positions"):
                enum = ", ".join(f"{pn} = {i}" for i, pn in enumerate(c["positions"]))
                body += f" enum Position : uint8_t {{ {enum} }};"
            o.append(f"struct {name}_t : {base} {{ {body} }};")
            o.append(f"constexpr {name}_t {name}{{}};")
        o.append(f"}} // namespace {p['code']}")
        o.append("")
    # Flash-resident lookup table for names (wiring test, debug text, bridge logs).
    o.append("/// Catalogue lookup table (sorted by id). Lives in flash on AVR.")
    o.append("inline const ControlInfo* catalogTable() {")
    for i, (p, c, cid) in enumerate(controls):
        o.append(f"    static const char n{i}[] HN_PROGMEM = {c_string(p['key'] + '.' + c['key'])};")
        if c.get("positions"):
            o.append(f"    static const char p{i}[] HN_PROGMEM = {c_string('|'.join(c['positions']))};")
    o.append("    static const ControlInfo table[] HN_PROGMEM = {")
    for i, (p, c, cid) in enumerate(controls):
        pos = f"p{i}" if c.get("positions") else "nullptr"
        flags = []
        if c.get("dcs") is None:
            flags.append("kInfoNoDcsData")
        if c["type"] in INPUT_TYPES:
            flags.append("kInfoInput")
        else:
            flags.append("kInfoOutput")
        if "guard" in c.get("flags", []):
            flags.append("kInfoGuard")
        if "magnetic" in c.get("flags", []):
            flags.append("kInfoMagnetic")
        if c.get("verified"):
            flags.append("kInfoVerified")
        o.append(f"        {{0x{cid:04X}, static_cast<uint8_t>(Kind::{KINDS[c['type']]}), {count_of(c)}, "
                 f"{' | '.join(flags)}, n{i}, {pos}}},")
    o.append("    };")
    o.append("    return table;")
    o.append("}")
    o.append("")
    o.append("} // namespace Hornet")
    return "\n".join(o) + "\n"


# ── Protocol constants ────────────────────────────────────────────────────

def render_spec(spec):
    o = ["#pragma once", f"// {HEADER_NOTE}", "// Source: catalog/protocol_v2.json. See docs/PROTOCOL_V2.md.", "",
         "#include <stdint.h>", "", "namespace hn {", ""]
    o.append(f"constexpr uint8_t kProtocolVersion = {spec['version']};")
    for k, v in spec["limits"].items():
        o.append(f"constexpr uint16_t k{camel(k)} = {v};")
    for k, v in spec["timing"].items():
        o.append(f"constexpr uint32_t kTiming{camel(k)} = {v}UL;")
    o.append("")
    o.append("/// Bus / link addresses.")
    o.append("enum Address : uint8_t {")
    for a in spec["addresses"]:
        o.append(f"    ADDR_{a['name']} = {a['value']}, ///< {a['description']}")
    o.append("};")
    o.append("")
    o.append("/// Message types (first header byte after version/dst/src).")
    o.append("enum MsgType : uint8_t {")
    for m in spec["messages"]:
        o.append(f"    MSG_{m['name']} = 0x{m['id']:02X}, ///< {m['description']}")
    o.append("};")
    for name, entries in spec["enums"].items():
        o.append("")
        o.append(f"enum {camel(name)}Code : uint8_t {{")
        for e in entries:
            o.append(f"    {name}_{e['name']} = {e['value']}, ///< {e['description']}")
        o.append("};")
    o.append("")
    o.append("/// Readable name of a message type (for logs and the ASCII debug mode).")
    o.append("inline const char* msgTypeName(uint8_t t) {")
    o.append("    switch (t) {")
    for m in spec["messages"]:
        o.append(f"    case MSG_{m['name']}: return \"{m['name']}\";")
    o.append("    default: return \"UNKNOWN\";")
    o.append("    }")
    o.append("}")
    o.append("")
    o.append("/// Readable name of a NACK reason.")
    o.append("inline const char* nackName(uint8_t r) {")
    o.append("    switch (r) {")
    for e in spec["enums"]["NACK"]:
        o.append(f"    case NACK_{e['name']}: return \"{e['name']}\";")
    o.append("    default: return \"UNKNOWN\";")
    o.append("    }")
    o.append("}")
    o.append("")
    o.append("} // namespace hn")
    return "\n".join(o) + "\n"


# ── Lua exporter ──────────────────────────────────────────────────────────

def lua_value(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, list):
        return "{ " + ", ".join(lua_value(x) for x in v) + " }"
    raise TypeError(v)


def render_lua(cat):
    rows = []
    for p, c, cid in all_controls(cat):
        dcs = c.get("dcs")
        if dcs is None:
            rows.append(f"    -- 0x{cid:04X} {p['key']}.{c['key']}: no DCS data yet")
            continue
        fields = [f"id = 0x{cid:04X}", f"name = {lua_value(p['key'] + '.' + c['key'])}",
                  f"type = {lua_value(c['type'])}"]
        if c.get("positions"):
            fields.append(f"count = {len(c['positions'])}")
        if c["type"] == "text":
            fields.append(f"length = {c['length']}")
        for k in ("style", "device", "command", "neg_command", "pos_command", "arg", "values",
                  "range", "threshold", "display", "field"):
            if k in dcs:
                fields.append(f"{k} = {lua_value(dcs[k])}")
        comment = "  -- DCS data: " + dcs["source"] + (" (TEMPORARY)" if dcs["source"] == "dcsbios" else "")
        rows.append("    { " + ", ".join(fields) + " }," + comment)
    table = "\n".join(rows)
    tpl = LUA_TEMPLATE.read_text(encoding="utf-8")
    return (tpl.replace("@@GENERATED_NOTE@@", HEADER_NOTE)
               .replace("@@CATALOG_HASH@@", f"0x{catalog_hash(cat):08X}")
               .replace("@@CATALOG_VERSION@@", cat["catalog_version"])
               .replace("@@AIRCRAFT@@", cat["aircraft"])
               .replace("@@CONTROLS@@", table))


# ── Markdown ──────────────────────────────────────────────────────────────

def md_escape(s):
    return s.replace("|", "\\|")


def render_reference(cat):
    o = ["# F/A-18C control reference", "", f"> {HEADER_NOTE} Source: `catalog/fa18c.json`.", "",
         f"Catalogue version **{cat['catalog_version']}**, hash **0x{catalog_hash(cat):08X}**, "
         f"{sum(len(p['controls']) for p in cat['panels'])} controls.", "",
         "Use the C++ name in sketches (for example `Hornet::MasterArm::MasterArm`) and the",
         "dotted name when reading logs or the ASCII debug output (`MASTER_ARM.MASTER_ARM=ARM`).",
         "Position constants are members of the control, e.g. `Hornet::MasterArm::MasterArm.ARM`.", "",
         "**Verified** means the entry was checked in a live DCS cockpit. **DCS data** shows where the",
         "DCS device, command and argument numbers came from; `dcsbios` entries are temporary and are",
         "listed in [DCS_DATA_PROVENANCE.md](DCS_DATA_PROVENANCE.md).", ""]
    for p in cat["panels"]:
        o.append(f"## {p['name']} (`Hornet::{p['code']}`, panel {p['id']})")
        o.append("")
        o.append("| ID | C++ name | Dotted name | Type | Positions / size | Flags | DCS data | Verified |")
        o.append("|---|---|---|---|---|---|---|---|")
        for c in p["controls"]:
            cid = (p["id"] << 8) | c["id"]
            if c.get("positions"):
                shape = ", ".join(f"`{x}`" for x in c["positions"])
            elif c["type"] == "text":
                shape = f"{c['length']} chars"
            elif c["type"] in ("axis", "gauge"):
                shape = "0-65535"
            elif c["type"] == "rotary":
                shape = "relative steps"
            else:
                shape = "on/off"
            dcs = c.get("dcs")
            src = dcs["source"] if dcs else "missing"
            o.append(f"| `0x{cid:04X}` | `{camel(c['key'])}` | `{p['key']}.{c['key']}` | {c['type']} | "
                     f"{shape} | {', '.join(c.get('flags', [])) or '-'} | {src} | "
                     f"{'yes' if c['verified'] else 'no'} |")
        o.append("")
    return "\n".join(o)


def render_messages(spec):
    o = ["# Protocol v2 message tables", "", f"> {HEADER_NOTE} Source: `catalog/protocol_v2.json`.", "",
         "Narrative, framing and bus rules: [PROTOCOL_V2.md](PROTOCOL_V2.md).", "",
         "## Messages", "", "| Name | Type | Direction | Payload | Meaning |", "|---|---|---|---|---|"]
    for m in spec["messages"]:
        o.append(f"| `{m['name']}` | `0x{m['id']:02X}` | {m['direction']} | `{md_escape(m['payload'])}` | "
                 f"{m['description']} |")
    o.append("")
    o.append("## Addresses")
    o.append("")
    o.append("| Name | Value | Meaning |")
    o.append("|---|---|---|")
    for a in spec["addresses"]:
        o.append(f"| `{a['name']}` | `0x{a['value']:02X}` | {a['description']} |")
    for name, entries in spec["enums"].items():
        o.append("")
        o.append(f"## {name} codes")
        o.append("")
        o.append("| Name | Value | Meaning |")
        o.append("|---|---|---|")
        for e in entries:
            o.append(f"| `{name}_{e['name']}` | {e['value']} | {e['description']} |")
    o.append("")
    o.append("## Limits and timing")
    o.append("")
    o.append("| Name | Value |")
    o.append("|---|---|")
    for k, v in list(spec["limits"].items()) + list(spec["timing"].items()):
        o.append(f"| `{k}` | {v} |")
    return "\n".join(o) + "\n"


def render_provenance(cat):
    src = cat["dcs_data_sources"]
    temp = [(p, c, cid) for p, c, cid in all_controls(cat)
            if c.get("dcs") and c["dcs"]["source"] == "dcsbios"]
    missing = [(p, c, cid) for p, c, cid in all_controls(cat) if not c.get("dcs")]
    o = ["# DCS data provenance register", "", f"> {HEADER_NOTE} Source: `catalog/fa18c.json`.", "",
         "Every catalogue entry records where its DCS device id, command code, argument number,",
         "argument values and indication field came from (`dcs.source`).", "",
         "## Temporary DCS-BIOS data - replace when native DCS data is available", ""]
    if "dcsbios" in src:
        s = src["dcsbios"]
        o += [f"- **What:** {s['description']}",
              f"- **From:** {s['url']} ({s.get('retrieved', 'date not recorded')})",
              f"- **Licence:** {s['license']}",
              f"- **Replace with:** {s['replace_with']}", ""]
    o += ["### How to replace an entry", "",
          "1. Read the device id, command and argument from the DCS install files named above.",
          "2. Check it in the cockpit (use the bridge decoder view or the ASCII debug mode).",
          "3. Edit the entry in `catalog/fa18c.json`: set `dcs.source` to a native source key",
          "   (add one under `dcs_data_sources`, e.g. `dcs-native`) and `verified` to `true`.",
          "4. Run `python3 Programs/tools/generate_hornet_catalog.py`. This register updates itself.",
          "   The catalogue hash does not change, because DCS data is not part of it.", "",
          "Other places that depend on DCS-BIOS and must change at the same time:", "",
          "- `Programs/dcsbios-serial-bridge/lua/HornetLinkNative.lua` - generated from the catalogue;",
          "  every row carrying `DCS data: dcsbios (TEMPORARY)` comes from this register.",
          "- The UFC/IFEI text controls use DCS indication field names seen in the DCS-BIOS module;",
          "  DCS-BIOS additionally pads and re-maps some of them (e.g. UFC two-digit displays).",
          "  The native exporter sends the raw text, padded to the catalogue length.",
          "- The legacy v1 path (`DcsBiosSource`, `HornetLinkExport.lua`, `docs/F18C_EXPORT_INVENTORY.md`)",
          "  is DCS-BIOS based by design and is kept only as a migration fallback.", "",
          f"### Entries ({len(temp)})", "",
          "| ID | Name | Style | Device | Command(s) | Arg | Values / range / field |",
          "|---|---|---|---|---|---|---|"]
    for p, c, cid in temp:
        d = c["dcs"]
        cmds = ", ".join(str(d[k]) for k in ("command", "neg_command", "pos_command") if k in d) or "-"
        extra = d.get("values") or d.get("range") or d.get("field") or d.get("threshold") or "-"
        if isinstance(extra, list):
            extra = ", ".join(str(x) for x in extra)
        if "display" in d:
            extra = f"display {d['display']}: {extra}"
        o.append(f"| `0x{cid:04X}` | `{p['key']}.{c['key']}` | {d['style']} | {d.get('device', '-')} | "
                 f"{cmds} | {d.get('arg', '-')} | {extra} |")
    o.append("")
    o.append(f"## Entries with no DCS data ({len(missing)})")
    o.append("")
    if missing:
        for p, c, cid in missing:
            o.append(f"- `0x{cid:04X}` `{p['key']}.{c['key']}`")
    else:
        o.append("None.")
    return "\n".join(o) + "\n"


def outputs():
    cat = load_catalog()
    spec = json.loads(PROTOCOL.read_text(encoding="utf-8"))
    return {
        OUT_CPP: render_cpp(cat),
        OUT_SPEC: render_spec(spec),
        OUT_LUA: render_lua(cat),
        OUT_REF: render_reference(cat),
        OUT_MSG: render_messages(spec),
        OUT_PROV: render_provenance(cat),
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if any output is out of date")
    ap.add_argument("--print-hash", action="store_true", help="print the catalogue hash and exit")
    args = ap.parse_args(argv)
    try:
        if args.print_hash:
            print(f"0x{catalog_hash(load_catalog()):08X}")
            return 0
        files = outputs()
    except (CatalogError, KeyError, ValueError) as e:
        print(f"catalogue error: {e}", file=sys.stderr)
        return 2
    stale = []
    for path, text in files.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    for path in stale:
        print(("stale: " if args.check else "wrote: ") + str(path.relative_to(ROOT)))
    return 1 if (args.check and stale) else 0


if __name__ == "__main__":
    sys.exit(main())
